spring:
#  RabbitMQ配置
  rabbitmq:
    host: 192.168.227.131
    username: guest
    password: guest
    virtual-host: /
    port: 5672
#    监听器
    listener:
      simple:
#        消费者最小数量
        concurrency: 10
#        消费者最大数量
        max-concurrency: 10
#        限制消费者每次只能处理一条消息，处理完毕后再继续处理下一条消息
        prefetch: 1
#        启动时是否默认启动容器
        auto-startup: true
#        消息被拒绝时重新进入队列
        default-requeue-rejected: true
#   模板
    template:
      retry:
#      开启重试：消息发送失败就重新发送
        enabled: true
#        重试时间
        initial-interval: 1000
#        重试最大次数
        max-attempts: 3
#        重试最大间隔时间
        max-interval: 10000
#        重试的间隔乘数：比如配置为2.0；则第一次等待10s，第二次等待20s，第三次等待40s
        multiplier: 1.0

#关闭thymeleaf缓存
  thymeleaf:
    cache: false

#数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: "0111"
    hikari:
      #连接池名字
      pool-name: DateHikariCP
      #最小空闲连接
      minimum-idle: 5
      #空闲连接最大存活时间
      idle-timeout: 1800000
      maximum-pool-size: 10
#      连接池返回的连接自动提交
      auto-commit: true
#      连接最大存活时间，默认既是半小时
      max-lifetime: 1800000
#      超时时间
      connection-timeout: 30000
#      测试连接是否可用
      connection-test-query: SELECT 1

#redis配置
  redis:
    #服务器地址
#    host: 192.168.3.109
    host: 192.168.227.131
    #端口
    port: 6379
    password: "0111"
    #数据库
    database: 0
    timeout: 10000ms
    #lettuce连接池
    lettuce:
      pool:
        #最大连接数：8
        max-active: 8
        #最大等待时机
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5


  web:
    resources:
      add-mappings: true
      cache:
        cachecontrol:
          max-age: 3600
      chain:
        cache: true
        enabled: true
        compressed: true
        html-application-cache: true
      static-locations: classpath:/static/

mybatis-plus:
#  配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
#  配置MyBatis数据返回类型别名
  type-aliases-package: com.gz.seckill.pojo

#打印日志：方法接口所在包
logging:
  level:
    com.gz.seckill.mapper: debug




